[packages.darwin]
brew = [
  "bash-completion@2",
  "fish",
  "fd",
  "fzf",
  "gh",
  "neovim",
  "ripgrep",
  "starship",
  "tmux",
  "zoxide",
]
cask = []

[packages.debian]
apt = [
  "build-essential",
  "bash-completion",
  "file",
  "zsh",
  "fish",
  "git",
  "procps",
  "curl",
  "fd-find",
  "fzf",
  "neovim",
  "ripgrep",
  "tmux",
]

[packages.ubuntu]
apt = [
  "build-essential",
  "bash-completion",
  "file",
  "zsh",
  "fish",
  "git",
  "procps",
  "curl",
  "fd-find",
  "fzf",
  "neovim",
  "ripgrep",
  "tmux",
]

[packages.uv]
tools = []

[packages.bun]
packages = []
